Repository Area-52-Percent/Cow-Duction, pull requests merged in 2019-12, with the labels that each got.

#18 Add start screen
  Cow-duction/Assets/Audio/Run Amok.wav.meta
  Cow-duction/Assets/Objects/Props.meta
  Cow-duction/Assets/Scenes/Nov20_DeVin.unity
  Cow-duction/Assets/Scenes/Start.unity
  Cow-duction/Assets/Scenes/Start.unity.meta
  Cow-duction/Assets/Scripts/Environment.meta
  Cow-duction/Assets/Scripts/Misc/CameraRotation.cs
  Cow-duction/Assets/Scripts/Misc/CameraRotation.cs.meta
  Cow-duction/Assets/Scripts/Misc/ResetButton.cs
  Cow-duction/Assets/Scripts/Misc/SwitchScene.cs
  Cow-duction/Assets/Scripts/Misc/SwitchScene.cs.meta
  Cow-duction/Assets/Source Images/UI/logo.png
  Cow-duction/Assets/Source Images/UI/logo.png.meta
  Cow-duction/Assets/Standard Assets/Environment.meta
  Cow-duction/ProjectSettings/EditorBuildSettings.asset
Labels: 3D, audio, enhancement

#19 Update grappling, add holograms and milk sliding effect
  Cow-duction/Assets/Animations/Cow/Cow.controller
  Cow-duction/Assets/Materials/Props/Hologram Blue.mat
  Cow-duction/Assets/Materials/Props/Hologram Blue.mat.meta
  Cow-duction/Assets/Materials/Props/Hologram Red.mat
  Cow-duction/Assets/Materials/Props/Hologram Red.mat.meta
  Cow-duction/Assets/Materials/Props/Hologram.shader
  Cow-duction/Assets/Materials/Props/Hologram.shader.meta
  Cow-duction/Assets/Objects/Props.meta
  Cow-duction/Assets/Prefabs/Characters/Bull.prefab
  Cow-duction/Assets/Prefabs/Characters/Cow.prefab
  Cow-duction/Assets/Prefabs/Environment/Windmill_Model.prefab
  Cow-duction/Assets/Scenes/Dec02_DeVin.meta
  Cow-duction/Assets/Scenes/Dec02_DeVin.unity
  Cow-duction/Assets/Scenes/Dec02_DeVin.unity.meta
  Cow-duction/Assets/Scenes/Dec02_DeVin/NavMesh.asset
  Cow-duction/Assets/Scenes/Dec02_DeVin/NavMesh.asset.meta
  Cow-duction/Assets/Scripts/Aliens/SC_AlienUIManager.cs
  Cow-duction/Assets/Scripts/Aliens/SC_CowAbduction.cs
  Cow-duction/Assets/Scripts/Aliens/SC_SpaceshipMovement.cs
  Cow-duction/Assets/Scripts/Cows/SC_CowBrain.cs
  Cow-duction/Assets/Scripts/Cows/SC_CowSpawner.cs
  Cow-duction/Assets/Scripts/Environment.meta
  Cow-duction/Assets/Scripts/Farmer/SC_FarmerBrain.cs
  Cow-duction/Assets/Scripts/Farmer/SC_Projectile.cs
  Cow-duction/Assets/Source Images/Props/flicker_smooth.png
  Cow-duction/Assets/Source Images/Props/flicker_smooth.png.meta
  Cow-duction/Assets/Source Images/UI/MilkSlide.png
  Cow-duction/Assets/Source Images/UI/MilkSlide.png.meta
  Cow-duction/ProjectSettings/EditorBuildSettings.asset
  Cow-duction/ProjectSettings/ProjectSettings.asset
Labels: 2D, 3D, code, enhancement

#21 High scores
  Cow-duction/Assets/Prefabs/Characters/Spaceship_v3.prefab
  Cow-duction/Assets/Scenes/Nov13_Vincent.unity
  Cow-duction/Assets/Scenes/Nov20_DeVin.unity
  Cow-duction/Assets/Scripts/Aliens/SC_AlienUIManager.cs
  Cow-duction/Assets/Scripts/Cows/SC_CowSpawner.cs
  Cow-duction/Assets/Scripts/Misc/HighScoreInput.cs
  Cow-duction/Assets/Scripts/Misc/HighScoreInput.cs.meta
  Cow-duction/Assets/Scripts/Misc/HighscoreTable.cs
  Cow-duction/Assets/Scripts/Misc/HighscoreTable.cs.meta
  Cow-duction/ProjectSettings/InputManager.asset
Labels: code, enhancement
