Repository Area-52-Percent/Cow-Duction, pull requests merged in 2020-02, with the labels that each got.

#32 Update Community Profile
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
Labels: documentation

#34 Make Contributing Guidelines more accessible
  .github/CONTRIBUTING.md
  Images/clone-repository-desktop.png
  README.md
Labels: documentation

#35 Optimized trees and added vert disp shader
  Cow-duction/Assets/Materials/Environment/Mat_TreeAl.mat
  Cow-duction/Assets/Materials/Environment/Mat_TreeAl.mat.meta
  Cow-duction/Assets/Materials/Shaders/Ver Disp Mat.mat
  Cow-duction/Assets/Objects/Environment/Greybox Terrain Feb 10/New Terrain 3.asset
  Cow-duction/Assets/Objects/Environment/Greybox Terrain Feb 10/TerrainData_4b88078d-9d6f-4461-8421-971bd0c71d6f.asset
  Cow-duction/Assets/Objects/Environment/Greybox Terrain Feb 10/TerrainData_682f525d-0308-4dd9-bf57-48a8f1b45849.asset
  Cow-duction/Assets/Objects/Environment/Greybox Terrain Feb 10/TerrainData_c327cfb7-e084-415b-a06d-a8e54dcc48ca.asset
  Cow-duction/Assets/Objects/Environment/PineTree_LowPoly.fbx
  Cow-duction/Assets/Objects/Environment/PineTree_LowPoly.fbx.meta
  Cow-duction/Assets/Objects/Environment/Tree_LowPoly.fbx
  Cow-duction/Assets/Objects/Environment/Tree_LowPoly.fbx.meta
  Cow-duction/Assets/Prefabs/Environment/TreeGrp.prefab
  Cow-duction/Assets/Prefabs/Environment/TreePrefab.prefab
  Cow-duction/Assets/Scenes/Feb20_NewTreesTest.unity
  Cow-duction/Assets/Scenes/Feb20_NewTreesTest.unity.meta
  Cow-duction/Assets/Source Images/Environment/TextureAlmanac_v01.psd
  Cow-duction/Assets/Source Images/Environment/TextureAlmanac_v01.psd.meta
Labels: 3D, enhancement, good first issue

#40 Wind turbine interaction
  Cow-duction/Assets/Prefabs/Environment/PlaceHolder_Windmill.prefab
  Cow-duction/Assets/Scripts/Environment/EnvironmentWind.cs
  Cow-duction/Assets/Scripts/Environment/WindmillEditor.cs
  Cow-duction/Assets/Scripts/Environment/WindmillEditor.cs.meta
Labels: 3D, code, enhancement
